<?php

namespace App\Models;

use Carbon\CarbonImmutable;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * @property int $id
 * @property int $apprentice_id
 * @property int $semester
 * @property int $year Generated by the database.
 * @property CarbonImmutable $start_date
 * @property CarbonImmutable $end_date
 */
#[Fillable(['apprentice_id', 'semester', 'start_date', 'end_date'])]
class ApprenticeshipPeriod extends Model
{
    public $timestamps = false;

    protected function casts(): array
    {
        return [
            'semester' => 'integer',
            'year' => 'integer',
            'start_date' => 'date',
            'end_date' => 'date',
        ];
    }

    /** @return BelongsTo<User, $this> */
    public function apprentice(): BelongsTo
    {
        return $this->belongsTo(User::class, 'apprentice_id');
    }

    /** @return HasMany<Grade, $this> */
    public function grades(): HasMany
    {
        return $this->hasMany(Grade::class, 'apprenticeship_periods_id');
    }
}
